# Generated by Django 5.2.1 on 2025-09-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mome_completo_alter_user_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mome_completo',
        ),
    ]
