# Generated by Django 6.0.2 on 2026-02-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_mome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
