# Generated by Django 6.0.2 on 2026-03-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_autorizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codigo',
        ),
    ]
