# Generated by Django 5.2.1 on 2025-09-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='multas.proprietario'),
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
