# Generated by Django 5.2.1 on 2025-09-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0002_proprietario_alter_veiculo_proprietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='matricula',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
