# Generated by Django 5.2.1 on 2025-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0003_alter_veiculo_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_lateralD',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_lateralE',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_traseira',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
