# Generated by Django 6.0.2 on 2026-03-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0004_veiculo_foto_frontal_veiculo_foto_laterald_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='agente',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
