# Generated by Django 6.0.2 on 2026-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0005_multa_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
