# Generated by Django 6.0.2 on 2026-03-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0006_veiculo_confirmada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='confirmada',
        ),
        migrations.AddField(
            model_name='multa',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
