# Generated by Django 6.0.2 on 2026-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0007_remove_veiculo_confirmada_multa_confirmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='tipo',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='velocidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
