# Generated by Django 6.0.2 on 2026-04-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0008_multa_tipo_multa_velocidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
    ]
