# Generated by Django 6.0.2 on 2026-04-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0009_multa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto/'),
        ),
    ]
