# Generated by Django 6.0.2 on 2026-04-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0010_alter_multa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
