# Generated by Django 6.0.2 on 2026-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0011_alter_multa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
